---
- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: "{{ item.path }}/.htpasswd"
    name: "{{ item.restic_htaccess_user }}"
    password: '{{ item.restic_htaccess_password }}'
    owner: "{{ restic_rest_user }}"
    group: "{{ restic_rest_group }}"
    mode: 0640
  with_items: '{{ restic_rest_repos }}'
  when:
    - restic_rest_repos.restic_rest_group is defined
    - restic_rest_repos.restic_rest_user is defined
    - restic_rest_repos.path is defined
