---
- name: install python-passlib
  package:
    name: python3-passlib
    state: present
  become: true

- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: "{{ item.path }}/.htpasswd"
    name: "{{ item.restic_htaccess_user }}"
    password: '{{ item.restic_htaccess_password }}'
    owner: "{{ restic_rest_user }}"
    group: "{{ restic_rest_group }}"
    mode: 0640
  when:
    - item.path is defined
    - item.restic_htaccess_user is defined
    - item.restic_htaccess_password is defined
  become: true
